<a href="https://colab.research.google.com/github/sravanikumku/ML/blob/main/knnbuiltin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np

In [31]:
import warnings
warnings.filterwarnings('ignore')

In [20]:
df=pd.read_csv("/content/drive/MyDrive/Iris.csv")
df=df.iloc[:,1:]

In [21]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.1)


In [22]:
x_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
104            6.5           3.0            5.8           2.2
114            5.8           2.8            5.1           2.4
118            7.7           2.6            6.9           2.3
24             4.8           3.4            1.9           0.2
83             6.0           2.7            5.1           1.6
115            6.4           3.2            5.3           2.3
143            6.8           3.2            5.9           2.3
26             5.0           3.4            1.6           0.4
54             6.5           2.8            4.6           1.5
35             5.0           3.2            1.2           0.2
52             6.9           3.1            4.9           1.5
120            6.9           3.2            5.7           2.3
44             5.1           3.8            1.9           0.4
18             5.7           3.8            1.7           0.3
95             5.7           3.0            4.2           1.2

In [23]:
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [24]:
x_test=np.array(x_test)
x_test

array([[6.5, 3. , 5.8, 2.2],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.6, 6.9, 2.3],
       [4.8, 3.4, 1.9, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [6.4, 3.2, 5.3, 2.3],
       [6.8, 3.2, 5.9, 2.3],
       [5. , 3.4, 1.6, 0.4],
       [6.5, 2.8, 4.6, 1.5],
       [5. , 3.2, 1.2, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.1, 3.8, 1.9, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.7, 3. , 4.2, 1.2]])

In [32]:
for i in range(len(x_test)):
  x=x_test[i]
  x_new=np.array([x])
  prediction=kn.predict(x_new)
  print("Target",y_test[i],"predicted",prediction)
print(kn.score(x_test,y_test))

Target Iris-virginica predicted ['Iris-virginica']
Target Iris-virginica predicted ['Iris-virginica']
Target Iris-virginica predicted ['Iris-virginica']
Target Iris-setosa predicted ['Iris-setosa']
Target Iris-versicolor predicted ['Iris-virginica']
Target Iris-virginica predicted ['Iris-virginica']
Target Iris-virginica predicted ['Iris-virginica']
Target Iris-setosa predicted ['Iris-setosa']
Target Iris-versicolor predicted ['Iris-versicolor']
Target Iris-setosa predicted ['Iris-setosa']
Target Iris-versicolor predicted ['Iris-versicolor']
Target Iris-virginica predicted ['Iris-virginica']
Target Iris-setosa predicted ['Iris-setosa']
Target Iris-setosa predicted ['Iris-setosa']
Target Iris-versicolor predicted ['Iris-versicolor']
0.9333333333333333


In [9]:
from sklearn.datasets import load_iris

In [10]:
dataset=load_iris()

In [13]:
dataset["data"]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
print(x_test[0])

[47.   5.1  3.8  1.6  0.2]


In [28]:
y_test=np.array(y_test)

In [29]:
y_test[0]

'Iris-virginica'